config/routes.rb
Rails.application.routes.draw do
  # get 'artists' => 'artists#index'
  # get 'artists/:id' => 'artists#show'
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
  @artist = Artist.create(artist_params)
  redirect_to @artist
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    redirect_to @artist
  end

  def show
    @artist = Artist.find(params[:id])
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @song = Song.all
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>
  <%= f.label :nationality %>
  <%= f.text_field :nationality %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<ul>
  <% @artists.each do |artist| %>

  <p><%= link_to artist.name, artist_path(artist)%></p>
      <p><%= artist.nationality %></p>
      <img src="<%= artist.photo_url %>">
      <p><%= link_to 'delete artist', artist_path(artist), method: :delete, data:{confirm: "Are you sure you want to delete this artist?"} %></p>
  <% end %>
</ul>
<h1><%= link_to "create new artist", new_artist_path %></h1>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>
  <%= f.label :nationality %>
  <%= f.text_field :nationality %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>nationality:</strong>
  <%= @artist.nationality %>
</p>

<img src="<%= @artist.photo_url %>">

<p><%= link_to "edit this artist", edit_artist_path(@artist) %></p>
<p><%= link_to 'delete this artist', artist_path(@artist), method: :delete, data:{confirm: "Are you sure you want to delete this artist?"} %></p>

<p><%= link_to 'Back', artists_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tunr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Artists", artists_path %></h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>Songs<a href="/songs/new">add song</a></h1>

<ul>
  <% @songs.each do |song| %>
    <li>
      <a href="/songs/<%= song.id %>">
      <%= song.title %> - <%= song.artist.name %>
      </a>
    </li>
  <% end %>

</ul>